// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.2
// LVGL version: 8.3.11
// Project name: Roboticarm

#include "ui.h"

void ui_event_comp_Switch2_Switch2(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t ** comp_Switch2 = lv_event_get_user_data(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_ScreenArm, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_ScreenArm_screen_init);
    }
}

// COMPONENT Switch2

lv_obj_t * ui_Switch2_create(lv_obj_t * comp_parent)
{

    lv_obj_t * cui_Switch2;
    cui_Switch2 = lv_switch_create(comp_parent);
    lv_obj_set_width(cui_Switch2, 256);
    lv_obj_set_height(cui_Switch2, 91);
    lv_obj_set_align(cui_Switch2, LV_ALIGN_CENTER);

    lv_obj_t ** children = lv_mem_alloc(sizeof(lv_obj_t *) * _UI_COMP_SWITCH2_NUM);
    children[UI_COMP_SWITCH2_SWITCH2] = cui_Switch2;
    lv_obj_add_event_cb(cui_Switch2, get_component_child_event_cb, LV_EVENT_GET_COMP_CHILD, children);
    lv_obj_add_event_cb(cui_Switch2, del_component_child_event_cb, LV_EVENT_DELETE, children);
    lv_obj_add_event_cb(cui_Switch2, ui_event_comp_Switch2_Switch2, LV_EVENT_ALL, children);
    ui_comp_Switch2_create_hook(cui_Switch2);
    return cui_Switch2;
}

