// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.2
// LVGL version: 8.3.11
// Project name: Roboticarm

#ifndef _UI_COMP_SWITCH2_H
#define _UI_COMP_SWITCH2_H

#include "ui.h"

#ifdef __cplusplus
extern "C" {
#endif

// COMPONENT Switch2
#define UI_COMP_SWITCH2_SWITCH2 0
#define _UI_COMP_SWITCH2_NUM 1
lv_obj_t * ui_Switch2_create(lv_obj_t * comp_parent);
void ui_event_comp_Switch2_Switch2(lv_event_t * e);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
