// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.2
// LVGL version: 8.3.11
// Project name: Roboticarm

#ifndef _UI_EVENTS_H
#define _UI_EVENTS_H

#ifdef __cplusplus
extern "C" {
#endif

void sliderBase_event_cb(lv_event_t * e);
void sliderWristRot_event_cb(lv_event_t * e);
void sliderShoulder_event_cb(lv_event_t * e);
void sliderElbow_event_cb(lv_event_t * e);
void sliderWristVer_event_cb(lv_event_t * e);
void sliderGripper_event_cb(lv_event_t * e);
void sliderSpeed_event_cb(lv_event_t * e);
void handleNewButtonEvent(lv_event_t *e);
void resetAllSliders(lv_event_t * e);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
