// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.2
// LVGL version: 8.3.11
// Project name: Roboticarm

#include "ui.h"




void sliderBase_event_cb(lv_event_t * e) {
    lv_obj_t * slider = lv_event_get_target(e);
    int val = lv_slider_get_value(slider);
    static char buf[8];
    snprintf(buf, sizeof(buf), "%d", val);
    lv_label_set_text(ui_labelBaseVal, buf);
}

void sliderShoulder_event_cb(lv_event_t * e) {
    lv_obj_t * slider = lv_event_get_target(e);
    int val = lv_slider_get_value(slider);
    static char buf[8];
    snprintf(buf, sizeof(buf), "%d", val);
    lv_label_set_text(ui_labelShoulderVal, buf);
}

void sliderElbow_event_cb(lv_event_t * e) {
    lv_obj_t * slider = lv_event_get_target(e);
    int val = lv_slider_get_value(slider);
    static char buf[8];
    snprintf(buf, sizeof(buf), "%d", val);
    lv_label_set_text(ui_labelElbowVal, buf);
}

void sliderWristVer_event_cb(lv_event_t * e) {
    lv_obj_t * slider = lv_event_get_target(e);
    int val = lv_slider_get_value(slider);
    static char buf[8];
    snprintf(buf, sizeof(buf), "%d", val);
    lv_label_set_text(ui_labelWristVerVal, buf);
}

void sliderWristRot_event_cb(lv_event_t * e) {
    lv_obj_t * slider = lv_event_get_target(e);
    int val = lv_slider_get_value(slider);
    static char buf[8];
    snprintf(buf, sizeof(buf), "%d", val);
    lv_label_set_text(ui_labelWristRotVal, buf);
}

void sliderGripper_event_cb(lv_event_t * e) {
    lv_obj_t * slider = lv_event_get_target(e);
    int val = lv_slider_get_value(slider);
    static char buf[8];
    snprintf(buf, sizeof(buf), "%d", val);
    lv_label_set_text(ui_labelGripperVal, buf);
}

void sliderSpeed_event_cb(lv_event_t * e) {
    lv_obj_t * slider = lv_event_get_target(e);
    int val = lv_slider_get_value(slider);
    static char buf[8];
    snprintf(buf, sizeof(buf), "%d", val);
    lv_label_set_text(ui_labelSpeedVal, buf);
}

