// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.2
// LVGL version: 8.3.11
// Project name: Roboticarm

#ifndef UI_SCREENARM_H
#define UI_SCREENARM_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_ScreenArm
extern void ui_ScreenArm_screen_init(void);
extern void ui_ScreenArm_screen_destroy(void);
extern lv_obj_t * ui_ScreenArm;
extern lv_obj_t * ui_Base;
extern lv_obj_t * ui_Shoulder;
extern lv_obj_t * ui_Elbow;
extern lv_obj_t * ui_Wrist_Pitch;
extern lv_obj_t * ui_Wrist_Roll;
extern lv_obj_t * ui_Wrist_Yaw;
extern lv_obj_t * ui_Gripper;
extern void ui_event_Button2(lv_event_t * e);
extern lv_obj_t * ui_Button2;
extern lv_obj_t * ui_Label4;
extern void ui_event_sliderBase(lv_event_t * e);
extern lv_obj_t * ui_sliderBase;
extern void ui_event_sliderWrist2(lv_event_t * e);
extern lv_obj_t * ui_sliderWrist2;
extern void ui_event_sliderShoulder(lv_event_t * e);
extern lv_obj_t * ui_sliderShoulder;
extern void ui_event_sliderElbow(lv_event_t * e);
extern lv_obj_t * ui_sliderElbow;
extern void ui_event_sliderWrist1(lv_event_t * e);
extern lv_obj_t * ui_sliderWrist1;
extern void ui_event_sliderWrist3(lv_event_t * e);
extern lv_obj_t * ui_sliderWrist3;
extern void ui_event_sliderGripper(lv_event_t * e);
extern lv_obj_t * ui_sliderGripper;
extern void ui_event_Button3(lv_event_t * e);
extern lv_obj_t * ui_Button3;
extern lv_obj_t * ui_Label5;
extern lv_obj_t * ui_btnSend;
extern lv_obj_t * ui_Label1;
extern lv_obj_t * ui_Resetbtn;
extern lv_obj_t * ui_Label3;
extern lv_obj_t * ui_labelBaseVal;
extern lv_obj_t * ui_labelShoulderVal;
extern lv_obj_t * ui_labelElbowVal;
extern lv_obj_t * ui_labelWristVerVal;
extern lv_obj_t * ui_labelWristRotVal;
extern lv_obj_t * ui_labelGripperVal;
extern lv_obj_t * ui_labelSpeedVal;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

