// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.2
// LVGL version: 8.3.11
// Project name: Roboticarm

#ifndef UI_SCREENPOWER_H
#define UI_SCREENPOWER_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_ScreenPower
extern void ui_ScreenPower_screen_init(void);
extern void ui_ScreenPower_screen_destroy(void);
extern lv_obj_t * ui_ScreenPower;
extern void ui_event_Button4(lv_event_t * e);
extern lv_obj_t * ui_Button4;
extern lv_obj_t * ui_Label2;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

